### ISSUE TITLE
Not outputting to .json

### ISSUE THREAD

**Issue by jakebresnehan** [cssstats/grunt-cssstats#3]
Hey @johnotander,

Any suggestions to why the outputted stats would not be writing to the `sample.json` file?

Should this be created on the fly it the file/folder doesn't exists?

```
    cssstats: {
      options: {
        safe: true
      },
      files: {
        'simple.json': ['style.css']
      }
    }
```

Cheers,
Jake

**Comment by johno** [comment]
That's strange. Is the relative path to the stylesheet correct?

**Comment by jakebresnehan** [comment]
Yeah it is correct.

No biggie. Just was keen to see some nice stats.

**Comment by johno** [comment]
If you aren't running `1.0.1`, I'd recommend upgrading. There was a bug in `cssstats` when parsing the `font` shorthand property. If that's in your CSS it could be what's causing it. I'm wondering if it's somehow failing silently as part of the grunt task.

**Comment by jakebresnehan** [comment]
I'm running `1.0.1` and also moved the stylesheet and the `.json` file into a subdirectory but still no :heart:  :cry:.

Running `grunt cssstats -v` give me an output:

```
File: [no files]
Options: safe
```

No stress. If I have time I'll try and re-create the issue in a new project. 

Thanks again.

**Comment by thotzl** [comment]
same here :wink:

**Comment by thotzl** [comment]
hey,
i know it's closed but had the same problem.

here is what i've done:

```
   cssstats: {
      options: { safe: true },
      'cssstats.json': ['public/css/pigstyle.css']
    },
```

... just removed the 'files'-knot :wink:

**Comment by johno** [comment]
Thanks for the comment @thotzl, I'm assuming it's working with your above Gruntfile?

**Comment by thotzl** [comment]
right!
